api = "0.2"

[buildpack]
  id = "paketo-buildpacks/go-dist"
  name = "Go Distribution Buildpack"
  homepage = "https://github.com/paketo-buildpacks/go-dist"

[metadata]
  include_files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml", "go.mod", "go.sum"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    go = "1.14.*"

  [[metadata.dependencies]]
    deprecation_date = "2020-09-03T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "171f8b81bc50c4efc1ecd618ad418edd4843556e65f2850167bb40ba57c81b48"
    source = "https://dl.google.com/go/go1.13.12.src.tar.gz"
    source_sha256 = "17ba2c4de4d78793a21cc659d9907f4356cd9c8de8b7d0899cdedcef712eba34"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.13.12_linux_x64_cflinuxfs3_171f8b81.tgz"
    version = "1.13.12"

  [[metadata.dependencies]]
    deprecation_date = "2020-09-03T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "3f0cac97dd2bb415a094b6ba59c1f528f3f8ac080094b544050ece6d2cfd35b0"
    source = "https://dl.google.com/go/go1.13.14.src.tar.gz"
    source_sha256 = "197333e97290e9ea8796f738d61019dcba1c377c2f3961fd6a114918ecc7ab06"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.13.14_linux_x64_cflinuxfs3_3f0cac97.tgz"
    version = "1.13.14"

  [[metadata.dependencies]]
    deprecation_date = "2021-02-25T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "73fa2a105323f57e3d13fe710d856e1438861aff561f5270d8d442ab004be857"
    source = "https://dl.google.com/go/go1.14.4.src.tar.gz"
    source_sha256 = "7011af3bbc2ac108d1b82ea8abb87b2e63f78844f0259be20cde4d42c5c40584"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.14.4_linux_x64_cflinuxfs3_73fa2a10.tgz"
    version = "1.14.4"

  [[metadata.dependencies]]
    deprecation_date = "2021-02-25T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "3f7111b6fa76d86421563a1cf768a90e1c8d3d5986926a72601d7e7e81884889"
    source = "https://dl.google.com/go/go1.14.5.src.tar.gz"
    source_sha256 = "ca4c080c90735e56152ac52cd77ae57fe573d1debb1a58e03da9cc362440315c"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.14.5_linux_x64_cflinuxfs3_3f7111b6.tgz"
    version = "1.14.5"

  [[metadata.dependency_deprecation_dates]]
    date = 2020-09-03T00:00:00Z
    link = "https://golang.org/doc/devel/release.html"
    name = "go"
    version_line = "1.13.x"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
