api = "0.5"

[buildpack]
  id = "paketo-buildpacks/go-dist"
  name = "Paketo Go Distribution Buildpack"
  homepage = "https://github.com/paketo-buildpacks/go-dist"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml", "go.mod", "go.sum"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    go = "1.16.*"

  [[metadata.dependencies]]
    deprecation_date = "2021-08-11T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "f3d831c0e1f3809461ae595dfb0d87792446834a7b3dd97417566827592e15b6"
    source = "https://dl.google.com/go/go1.15.11.src.tar.gz"
    source_sha256 = "f25b2441d4c76cf63cde94d59bab237cc33e8a2a139040d904c8630f46d061e5"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.15.11_linux_x64_cflinuxfs3_f3d831c0.tgz"
    version = "1.15.11"

  [[metadata.dependencies]]
    deprecation_date = "2021-08-11T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "31eefdc6e2dc842cfdc926796e23f6ff1e6b4de7ec1b6a0dceed580344ec612c"
    source = "https://dl.google.com/go/go1.15.12.src.tar.gz"
    source_sha256 = "1c6911937df4a277fa74e7b7efc3d08594498c4c4adc0b6c4ae3566137528091"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.15.12_linux_x64_cflinuxfs3_31eefdc6.tgz"
    version = "1.15.12"

  [[metadata.dependencies]]
    id = "go"
    name = "Go"
    sha256 = "da880dda8543634d24cfcfabfd19cd0938db88987cdfac253651ca6831364707"
    source = "https://dl.google.com/go/go1.16.2.src.tar.gz"
    source_sha256 = "37ca14287a23cb8ba2ac3f5c3dd8adbc1f7a54b9701a57824bf19a0b271f83ea"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.16.2_linux_x64_cflinuxfs3_da880dda.tgz"
    version = "1.16.2"

  [[metadata.dependencies]]
    id = "go"
    name = "Go"
    sha256 = "03d690e4dd7064fef2f2c3049b7dc7837478a3a4f81ff436ac12f7f9bcb9aa2b"
    source = "https://dl.google.com/go/go1.16.3.src.tar.gz"
    source_sha256 = "b298d29de9236ca47a023e382313bcc2d2eed31dfa706b60a04103ce83a71a25"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.16.3_linux_x64_cflinuxfs3_03d690e4.tgz"
    version = "1.16.3"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
