api = "0.4"

[buildpack]
  id = "paketo-buildpacks/go-dist"
  name = "Paketo Go Distribution Buildpack"
  homepage = "https://github.com/paketo-buildpacks/go-dist"

[metadata]
  include_files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml", "go.mod", "go.sum"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    go = "1.15.*"

  [[metadata.dependencies]]
    deprecation_date = "2021-02-25T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "0f657a419b317dab4ff8b62cfdeab69c0bcad25458bf454cb79b61da05c1ac54"
    source = "https://dl.google.com/go/go1.14.9.src.tar.gz"
    source_sha256 = "c687c848cc09bcabf2b5e534c3fc4259abebbfc9014dd05a1a2dc6106f404554"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.14.9_linux_x64_cflinuxfs3_0f657a41.tgz"
    version = "1.14.9"

  [[metadata.dependencies]]
    deprecation_date = "2021-02-25T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "f573390de4a8c08216f75046852f769848c20873ec60104beb623888518fa88f"
    source = "https://dl.google.com/go/go1.14.10.src.tar.gz"
    source_sha256 = "b37699a7e3eab0f90412b3969a90fd072023ecf61e0b86369da532810a95d665"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.14.10_linux_x64_cflinuxfs3_f573390d.tgz"
    version = "1.14.10"

  [[metadata.dependencies]]
    deprecation_date = "2021-08-11T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "23ddc5e3ea80eabc8547ddb283d019a2dbb50dc2cbca677e7bd1f01327bda283"
    source = "https://dl.google.com/go/go1.15.2.src.tar.gz"
    source_sha256 = "28bf9d0bcde251011caae230a4a05d917b172ea203f2a62f2c2f9533589d4b4d"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.15.2_linux_x64_cflinuxfs3_23ddc5e3.tgz"
    version = "1.15.2"

  [[metadata.dependencies]]
    deprecation_date = "2021-08-11T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "dd49c88e48eba4dfb33854aa4dfd205897f73998e015ee6bd0188f5d13c3ecfc"
    source = "https://dl.google.com/go/go1.15.3.src.tar.gz"
    source_sha256 = "896a602570e54c8cdfc2c1348abd4ffd1016758d0bd086ccd9787dbfc9b64888"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.15.3_linux_x64_cflinuxfs3_dd49c88e.tgz"
    version = "1.15.3"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
