api = "0.4"

[buildpack]
  id = "paketo-buildpacks/go-dist"
  name = "Paketo Go Distribution Buildpack"
  homepage = "https://github.com/paketo-buildpacks/go-dist"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml", "go.mod", "go.sum"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    go = "1.15.*"

  [[metadata.dependencies]]
    deprecation_date = "2021-02-25T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "48d06585c8fe0694377b9772aac0e17e202817e8dc79336207ff890e5b794387"
    source = "https://dl.google.com/go/go1.14.11.src.tar.gz"
    source_sha256 = "1871f3d29b0cf1ebb739c9b134c9bc559282bd3625856e5f12f5aea29ab70f16"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.14.11_linux_x64_cflinuxfs3_48d06585.tgz"
    version = "1.14.11"

  [[metadata.dependencies]]
    deprecation_date = "2021-02-25T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "df335fd03d21cf1ea4d89e691bef1c012b542fc7d7d293dcbf957cabaeeab4e0"
    source = "https://dl.google.com/go/go1.14.12.src.tar.gz"
    source_sha256 = "b34f4b7ad799eab4c1a52bdef253602ce957125a512f5a1b28dce43c6841b971"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.14.12_linux_x64_cflinuxfs3_df335fd0.tgz"
    version = "1.14.12"

  [[metadata.dependencies]]
    deprecation_date = "2021-08-11T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "fd04494f7a2dd478b0d31cb949aae7f154749cae1242581b1574f7e590b3b7e6"
    source = "https://dl.google.com/go/go1.15.5.src.tar.gz"
    source_sha256 = "c1076b90cf94b73ebed62a81d802cd84d43d02dea8c07abdc922c57a071c84f1"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.15.5_linux_x64_cflinuxfs3_fd04494f.tgz"
    version = "1.15.5"

  [[metadata.dependencies]]
    deprecation_date = "2021-08-11T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "894a010e8240ef9e5bc62d1472110ad00eafc60ab53dee93ea01af17c00ab1f9"
    source = "https://dl.google.com/go/go1.15.6.src.tar.gz"
    source_sha256 = "890bba73c5e2b19ffb1180e385ea225059eb008eb91b694875dd86ea48675817"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.15.6_linux_x64_cflinuxfs3_894a010e.tgz"
    version = "1.15.6"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
