api = "0.2"

[buildpack]
  id = "paketo-buildpacks/go-dist"
  name = "Paketo Go Distribution Buildpack"
  homepage = "https://github.com/paketo-buildpacks/go-dist"

[metadata]
  include_files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml", "go.mod", "go.sum"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    go = "1.14.*"

  [[metadata.dependencies]]
    deprecation_date = "2020-09-03T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "3f0cac97dd2bb415a094b6ba59c1f528f3f8ac080094b544050ece6d2cfd35b0"
    source = "https://dl.google.com/go/go1.13.14.src.tar.gz"
    source_sha256 = "197333e97290e9ea8796f738d61019dcba1c377c2f3961fd6a114918ecc7ab06"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.13.14_linux_x64_cflinuxfs3_3f0cac97.tgz"
    version = "1.13.14"

  [[metadata.dependencies]]
    deprecation_date = "2020-09-03T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "0374546870b055b01e4aea14fd05cc30dd4bda45f46a48c3cb960167a95afb96"
    source = "https://dl.google.com/go/go1.13.15.src.tar.gz"
    source_sha256 = "5fb43171046cf8784325e67913d55f88a683435071eef8e9da1aa8a1588fcf5d"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.13.15_linux_x64_cflinuxfs3_03745468.tgz"
    version = "1.13.15"

  [[metadata.dependencies]]
    deprecation_date = "2021-02-25T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "dae88e8007806194ad81aec74cc7f068c2ccc32615adea0ea7c88b593ee080ed"
    source = "https://dl.google.com/go/go1.14.6.src.tar.gz"
    source_sha256 = "73fc9d781815d411928eccb92bf20d5b4264797be69410eac854babe44c94c09"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.14.6_linux_x64_cflinuxfs3_dae88e80.tgz"
    version = "1.14.6"

  [[metadata.dependencies]]
    deprecation_date = "2021-02-25T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "edc2c096989a90d57cd023785a686f0b9bfe945bb8b22f2a92cd51fda25cadd9"
    source = "https://dl.google.com/go/go1.14.7.src.tar.gz"
    source_sha256 = "064392433563660c73186991c0a315787688e7c38a561e26647686f89b6c30e3"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.14.7_linux_x64_cflinuxfs3_edc2c096.tgz"
    version = "1.14.7"

  [[metadata.dependencies]]
    deprecation_date = "2021-08-11T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "4e73b8b4b0855f92501650dbf4bdfda96d78eef855a3560b77f5892f824b4e3f"
    source = "https://dl.google.com/go/go1.15.src.tar.gz"
    source_sha256 = "69438f7ed4f532154ffaf878f3dfd83747e7a00b70b3556eddabf7aaee28ac3a"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.15_linux_x64_cflinuxfs3_4e73b8b4.tgz"
    version = "1.15"

  [[metadata.dependency_deprecation_dates]]
    date = 2020-09-03T00:00:00Z
    link = "https://golang.org/doc/devel/release.html"
    name = "go"
    version_line = "1.13.x"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
