api = "0.2"

[buildpack]
  id = "paketo-buildpacks/go-compiler"
  name = "Go Compiler Buildpack"
  version = ""
  homepage = "https://github.com/paketo-buildpacks/go-compiler"

[metadata]
  include_files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml", "go.mod", "go.sum"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    go = "1.13.*"

  [[metadata.dependencies]]
    deprecation_date = "2020-09-03T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "1735a40c3f1085a7862d7c4b4e1bb73946c4a399e771ceb32845f2c9646e24d5"
    source = "https://dl.google.com/go/go1.13.10.src.tar.gz"
    source_sha256 = "eb9ccc8bf59ed068e7eff73e154e4f5ee7eec0a47a610fb864e3332a2fdc8b8c"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.13.10_linux_x64_cflinuxfs3_1735a40c.tgz"
    version = "1.13.10"

  [[metadata.dependencies]]
    deprecation_date = "2020-09-03T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "2121cff4d44a95cd1069bb287f4790471e85ddcbc9055cb1cc768a326bc006f6"
    source = "https://dl.google.com/go/go1.13.11.src.tar.gz"
    source_sha256 = "89ed1abce25ad003521c125d6583c93c1280de200ad221f961085200a6c00679"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.13.11_linux_x64_cflinuxfs3_2121cff4.tgz"
    version = "1.13.11"

  [[metadata.dependencies]]
    deprecation_date = "2021-02-25T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "a9579c40c6ecca06f7c40ff7563b259cfe33bd20c0611d6c48a76c3811bff8c2"
    source = "https://dl.google.com/go/go1.14.3.src.tar.gz"
    source_sha256 = "93023778d4d1797b7bc6a53e86c3a9b150c923953225f8a48a2d5fabc971af56"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.14.3_linux_x64_cflinuxfs3_a9579c40.tgz"
    version = "1.14.3"

  [[metadata.dependencies]]
    deprecation_date = "2021-02-25T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "73fa2a105323f57e3d13fe710d856e1438861aff561f5270d8d442ab004be857"
    source = "https://dl.google.com/go/go1.14.4.src.tar.gz"
    source_sha256 = "7011af3bbc2ac108d1b82ea8abb87b2e63f78844f0259be20cde4d42c5c40584"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.14.4_linux_x64_cflinuxfs3_73fa2a10.tgz"
    version = "1.14.4"

  [[metadata.dependency_deprecation_dates]]
    date = 2020-09-03T00:00:00Z
    link = "https://golang.org/doc/devel/release.html"
    name = "go"
    version_line = "1.13.x"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
  id = "org.cloudfoundry.stacks.tiny"
