api = "0.5"

[buildpack]
  id = "paketo-buildpacks/go-dist"
  name = "Paketo Go Distribution Buildpack"
  homepage = "https://github.com/paketo-buildpacks/go-dist"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml", "go.mod", "go.sum"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    go = "1.16.*"

  [[metadata.dependencies]]
    deprecation_date = "2021-08-11T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "f3d831c0e1f3809461ae595dfb0d87792446834a7b3dd97417566827592e15b6"
    source = "https://dl.google.com/go/go1.15.11.src.tar.gz"
    source_sha256 = "f25b2441d4c76cf63cde94d59bab237cc33e8a2a139040d904c8630f46d061e5"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.15.11_linux_x64_cflinuxfs3_f3d831c0.tgz"
    version = "1.15.11"

  [[metadata.dependencies]]
    deprecation_date = "2021-08-11T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "31eefdc6e2dc842cfdc926796e23f6ff1e6b4de7ec1b6a0dceed580344ec612c"
    source = "https://dl.google.com/go/go1.15.12.src.tar.gz"
    source_sha256 = "1c6911937df4a277fa74e7b7efc3d08594498c4c4adc0b6c4ae3566137528091"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.15.12_linux_x64_cflinuxfs3_31eefdc6.tgz"
    version = "1.15.12"

  [[metadata.dependencies]]
    id = "go"
    name = "Go"
    sha256 = "f5a9da8a05882104403de726b7e4c222f9ace214957d8d9641c9c8fcf9865edb"
    source = "https://dl.google.com/go/go1.16.4.src.tar.gz"
    source_sha256 = "ae4f6b6e2a1677d31817984655a762074b5356da50fb58722b99104870d43503"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.16.4_linux_x64_cflinuxfs3_f5a9da8a.tgz"
    version = "1.16.4"

  [[metadata.dependencies]]
    id = "go"
    name = "Go"
    sha256 = "89520cb99f93060a3cf2598456c676d24377edbf9d3af524b939f6bf0ce6b6b9"
    source = "https://dl.google.com/go/go1.16.5.src.tar.gz"
    source_sha256 = "7bfa7e5908c7cc9e75da5ddf3066d7cbcf3fd9fa51945851325eebc17f50ba80"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.16.5_linux_x64_cflinuxfs3_89520cb9.tgz"
    version = "1.16.5"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
