api = "0.4"

[buildpack]
  id = "paketo-buildpacks/go-dist"
  name = "Paketo Go Distribution Buildpack"
  homepage = "https://github.com/paketo-buildpacks/go-dist"

[metadata]
  include_files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml", "go.mod", "go.sum"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    go = "1.15.*"

  [[metadata.dependencies]]
    deprecation_date = "2021-02-25T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "6c94e519ac658acf9cc1b2d1482759320320cddee1837618397228bab7bca7ef"
    source = "https://dl.google.com/go/go1.14.8.src.tar.gz"
    source_sha256 = "d9a613fb55f508cf84e753456a7c6a113c8265839d5b7fe060da335c93d6e36a"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.14.8_linux_x64_cflinuxfs3_6c94e519.tgz"
    version = "1.14.8"

  [[metadata.dependencies]]
    deprecation_date = "2021-02-25T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "0f657a419b317dab4ff8b62cfdeab69c0bcad25458bf454cb79b61da05c1ac54"
    source = "https://dl.google.com/go/go1.14.9.src.tar.gz"
    source_sha256 = "c687c848cc09bcabf2b5e534c3fc4259abebbfc9014dd05a1a2dc6106f404554"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.14.9_linux_x64_cflinuxfs3_0f657a41.tgz"
    version = "1.14.9"

  [[metadata.dependencies]]
    deprecation_date = "2021-08-11T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "2812dfd3e1ad9481372b247eaf6bd7af0b81b6bb3a32a2b4d153d9f1d56e61f1"
    source = "https://dl.google.com/go/go1.15.1.src.tar.gz"
    source_sha256 = "d3743752a421881b5cc007c76b4b68becc3ad053e61275567edab1c99e154d30"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.15.1_linux_x64_cflinuxfs3_2812dfd3.tgz"
    version = "1.15.1"

  [[metadata.dependencies]]
    deprecation_date = "2021-08-11T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "23ddc5e3ea80eabc8547ddb283d019a2dbb50dc2cbca677e7bd1f01327bda283"
    source = "https://dl.google.com/go/go1.15.2.src.tar.gz"
    source_sha256 = "28bf9d0bcde251011caae230a4a05d917b172ea203f2a62f2c2f9533589d4b4d"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.15.2_linux_x64_cflinuxfs3_23ddc5e3.tgz"
    version = "1.15.2"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
