api = "0.2"

[buildpack]
  id = "paketo-buildpacks/go-compiler"
  name = "Go Compiler Buildpack"
  version = "{{ .Version }}"
  homepage = "https://github.com/paketo-buildpacks/go-compiler"

[metadata]
  include_files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml", "go.mod", "go.sum"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    go = "1.13.*"

  [[metadata.dependencies]]
    deprecation_date = "2020-09-03T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "3fd7140d9c6de45a46fd261b68db7312a669d0d54ff2dd6faa8215fa990171b4"
    source = "https://dl.google.com/go/go1.13.10.linux-amd64.tar.gz"
    source_sha256 = "8a4cbc9f2b95d114c38f6cbe94a45372d48c604b707db2057c787398dfbf8e7f"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go-1.13.10-bionic-3fd7140d.tgz"
    version = "1.13.10"

  [[metadata.dependencies]]
    deprecation_date = "2020-09-03T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "676f441b1f043f7ccb875906bd5869d630af3ff0db36c805677e8aa60e67c86a"
    source = "https://dl.google.com/go/go1.13.10.src.tar.gz"
    source_sha256 = "eb9ccc8bf59ed068e7eff73e154e4f5ee7eec0a47a610fb864e3332a2fdc8b8c"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.13.10_linux_x64_cflinuxfs3_676f441b.tgz"
    version = "1.13.10"

  [[metadata.dependencies]]
    deprecation_date = "2020-09-03T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "5bca0d629672ea59fd9750ad9f0d1cd8faea692fe2af2a109b698fe56f4e7b7b"
    source = "https://dl.google.com/go/go1.13.10.linux-amd64.tar.gz"
    source_sha256 = "8a4cbc9f2b95d114c38f6cbe94a45372d48c604b707db2057c787398dfbf8e7f"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go-1.13.10-tiny-5bca0d62.tgz"
    version = "1.13.10"

  [[metadata.dependencies]]
    deprecation_date = "2020-09-03T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "2121cff4d44a95cd1069bb287f4790471e85ddcbc9055cb1cc768a326bc006f6"
    source = "https://dl.google.com/go/go1.13.11.src.tar.gz"
    source_sha256 = "89ed1abce25ad003521c125d6583c93c1280de200ad221f961085200a6c00679"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.13.11_linux_x64_cflinuxfs3_2121cff4.tgz"
    version = "1.13.11"

  [[metadata.dependencies]]
    deprecation_date = "2021-02-25T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "45795fb446e7a3e08daee393e7550ec4a5fb75295e3e97a5a20e932e78706455"
    source = "https://dl.google.com/go/go1.14.2.linux-amd64.tar.gz"
    source_sha256 = "6272d6e940ecb71ea5636ddb5fab3933e087c1356173c61f4a803895e947ebb3"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go-1.14.2-bionic-45795fb4.tgz"
    version = "1.14.2"

  [[metadata.dependencies]]
    deprecation_date = "2021-02-25T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "11e7a4512af39fabddb558f88a7162a530e3136b1204f293d164b5d9ecc59ad0"
    source = "https://dl.google.com/go/go1.14.2.src.tar.gz"
    source_sha256 = "98de84e69726a66da7b4e58eac41b99cbe274d7e8906eeb8a5b7eb0aadee7f7c"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.14.2_linux_x64_cflinuxfs3_11e7a451.tgz"
    version = "1.14.2"

  [[metadata.dependencies]]
    deprecation_date = "2021-02-25T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "0572685e9eb1333b6d8e76953fdbbbf8531575f45301434a188cd22ded93d958"
    source = "https://dl.google.com/go/go1.14.2.linux-amd64.tar.gz"
    source_sha256 = "6272d6e940ecb71ea5636ddb5fab3933e087c1356173c61f4a803895e947ebb3"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go-1.14.2-tiny-0572685e.tgz"
    version = "1.14.2"

  [[metadata.dependencies]]
    deprecation_date = "2021-02-25T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "a9579c40c6ecca06f7c40ff7563b259cfe33bd20c0611d6c48a76c3811bff8c2"
    source = "https://dl.google.com/go/go1.14.3.src.tar.gz"
    source_sha256 = "93023778d4d1797b7bc6a53e86c3a9b150c923953225f8a48a2d5fabc971af56"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.14.3_linux_x64_cflinuxfs3_a9579c40.tgz"
    version = "1.14.3"

  [[metadata.dependency_deprecation_dates]]
    date = 2020-09-03T00:00:00Z
    link = "https://golang.org/doc/devel/release.html"
    name = "go"
    version_line = "1.13.x"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
  id = "org.cloudfoundry.stacks.tiny"
