api = "0.4"

[buildpack]
  id = "paketo-buildpacks/go-dist"
  name = "Paketo Go Distribution Buildpack"
  homepage = "https://github.com/paketo-buildpacks/go-dist"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml", "go.mod", "go.sum"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    go = "1.15.*"

  [[metadata.dependencies]]
    deprecation_date = "2021-02-25T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "2b6ff1d4025212d18db2c238cc6381b46c8da0e01de95705343ae529edb28e90"
    source = "https://dl.google.com/go/go1.14.14.src.tar.gz"
    source_sha256 = "6204bf32f58fae0853f47f1bd0c51d9e0ac11f1ffb406bed07a0a8b016c8a76f"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.14.14_linux_x64_cflinuxfs3_2b6ff1d4.tgz"
    version = "1.14.14"

  [[metadata.dependencies]]
    deprecation_date = "2021-02-25T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "89d135ef839026f79e784712a58fef354beaee0e9c79a57c3962c45b18026102"
    source = "https://dl.google.com/go/go1.14.15.src.tar.gz"
    source_sha256 = "7ed13b2209e54a451835997f78035530b331c5b6943cdcd68a3d815fdc009149"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.14.15_linux_x64_cflinuxfs3_89d135ef.tgz"
    version = "1.14.15"

  [[metadata.dependencies]]
    deprecation_date = "2021-08-11T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "894a010e8240ef9e5bc62d1472110ad00eafc60ab53dee93ea01af17c00ab1f9"
    source = "https://dl.google.com/go/go1.15.6.src.tar.gz"
    source_sha256 = "890bba73c5e2b19ffb1180e385ea225059eb008eb91b694875dd86ea48675817"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.15.6_linux_x64_cflinuxfs3_894a010e.tgz"
    version = "1.15.6"

  [[metadata.dependencies]]
    deprecation_date = "2021-08-11T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "fa481c843585d4618a561109dd772857b73bca0fb2439f5e4bda1488c40ab77c"
    source = "https://dl.google.com/go/go1.15.7.src.tar.gz"
    source_sha256 = "8631b3aafd8ecb9244ec2ffb8a2a8b4983cf4ad15572b9801f7c5b167c1a2abc"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.15.7_linux_x64_cflinuxfs3_fa481c84.tgz"
    version = "1.15.7"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
