api = "0.4"

[buildpack]
  id = "paketo-buildpacks/go-dist"
  name = "Paketo Go Distribution Buildpack"
  homepage = "https://github.com/paketo-buildpacks/go-dist"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml", "go.mod", "go.sum"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    go = "1.15.*"

  [[metadata.dependencies]]
    deprecation_date = "2021-02-25T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "2b6ff1d4025212d18db2c238cc6381b46c8da0e01de95705343ae529edb28e90"
    source = "https://dl.google.com/go/go1.14.14.src.tar.gz"
    source_sha256 = "6204bf32f58fae0853f47f1bd0c51d9e0ac11f1ffb406bed07a0a8b016c8a76f"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.14.14_linux_x64_cflinuxfs3_2b6ff1d4.tgz"
    version = "1.14.14"

  [[metadata.dependencies]]
    deprecation_date = "2021-02-25T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "89d135ef839026f79e784712a58fef354beaee0e9c79a57c3962c45b18026102"
    source = "https://dl.google.com/go/go1.14.15.src.tar.gz"
    source_sha256 = "7ed13b2209e54a451835997f78035530b331c5b6943cdcd68a3d815fdc009149"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.14.15_linux_x64_cflinuxfs3_89d135ef.tgz"
    version = "1.14.15"

  [[metadata.dependencies]]
    deprecation_date = "2021-08-11T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "cd5a88c603caa848f47424bf2401ab7d256d181b2f1e77a79bf6d7dab69b7782"
    source = "https://dl.google.com/go/go1.15.8.src.tar.gz"
    source_sha256 = "540c0ab7781084d124991321ed1458e479982de94454a98afab6acadf38497c2"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.15.8_linux_x64_cflinuxfs3_cd5a88c6.tgz"
    version = "1.15.8"

  [[metadata.dependencies]]
    deprecation_date = "2021-08-11T00:00:00Z"
    id = "go"
    name = "Go"
    sha256 = "7fef8ba6a0786143efcce66b0bbfbfbab02afeef522b4e09833c5b550d7741ad"
    source = "https://dl.google.com/go/go1.15.9.src.tar.gz"
    source_sha256 = "90983b9c84a92417337dc1942ff066fc8b3a69733b8b5493fd0b9b9db1ead60f"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.15.9_linux_x64_cflinuxfs3_7fef8ba6.tgz"
    version = "1.15.9"

  [[metadata.dependencies]]
    id = "go"
    name = "Go"
    sha256 = "c5f8cca1958fc434ce8312cf89514d7ec101b8360c9c8d5c5b70b6b27840d2a7"
    source = "https://dl.google.com/go/go1.16.1.src.tar.gz"
    source_sha256 = "680a500cd8048750121677dd4dc055fdfd680ae83edc7ed60a4b927e466228eb"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.16.1_linux_x64_cflinuxfs3_c5f8cca1.tgz"
    version = "1.16.1"

  [[metadata.dependencies]]
    id = "go"
    name = "Go"
    sha256 = "da880dda8543634d24cfcfabfd19cd0938db88987cdfac253651ca6831364707"
    source = "https://dl.google.com/go/go1.16.2.src.tar.gz"
    source_sha256 = "37ca14287a23cb8ba2ac3f5c3dd8adbc1f7a54b9701a57824bf19a0b271f83ea"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/go/go_1.16.2_linux_x64_cflinuxfs3_da880dda.tgz"
    version = "1.16.2"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
